volumes:
  mysql_volume: {}

services:
  mysql:
    build: docker/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=${APP_TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - TZ=${APP_TIMEZONE}
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    restart: unless-stopped
